### ISSUE TITLE
startPayroll Command can only be run once

### ISSUE THREAD

**Issue by boonhaii** [AY2122S1-CS2103T-F11-3/tp#114]
To replicate the bug:
1. Type in the command `startPayroll`
2. Type in the command `pay all`
3. Type in the command `startPayroll` again. The user feedback panel should display "Payroll done" text and there are no changes to the list panel.

**Comment by szelongq** [comment]
Reason behind behaviour was that after the first `startPayroll` and `pay all` commands, all employees have their hours worked and overtime set to zero. As a result, subsequent `startPayroll` commands will calculate their pay as zero and they are not owed any money, hence visually looks the same.
