### ISSUE TITLE
[PE-D] unintended interaction with deductHoursWorked command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-F11-3/tp#158]
This is a valid command 
![image.png](https://raw.githubusercontent.com/syoopie/ped/main/files/14941985-24a4-4409-a5ab-0a72e503f784.png)
it is `deductHoursWorked 1 hw/1 o/2` copypasted multiple times

not sure if this bug will be present in other commands as well

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: syoopie/ped#12

**Comment by szelongq** [comment]
Thank you for the suggestion, but actually it was mentioned earlier in the User Guide that for duplicate fields, only the last entry will be taken. And in this case, the input was indeed valid hence no error message is produced, this is not a bug.
