### ISSUE TITLE
[PE-D] Logging inconsistencies

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-F11-3/tp#160]
The logs dont show Overtime hours

![image.png](https://raw.githubusercontent.com/syoopie/ped/main/files/c18291d3-b07c-449c-a823-1dc92c130464.png)

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: syoopie/ped#13

**Comment by szelongq** [comment]
Thank you for the suggestion, but we believe that logging is out-of-scope for our project as users are not expected to use it.
